### ISSUE TITLE
Funding overlap validation bug causing Roster infinite load

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1137]
## Background
User-reported roster is stuck in infinite load. Determined cause is 500 response to `children` query caused by:
```
2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: query: SELECT "Enrollment"."id" AS "Enrollment_id", "Enrollment"."childId" AS "Enrollment_childId", "Enrollment"."siteId" AS "Enrollment_siteId", "Enrollment"."model" AS "Enrollment_model", "Enrollment"."ageGroup" AS "Enrollment_ageGroup", "Enrollment"."entry" AS "Enrollment_entry", "Enrollment"."exit" AS "Enrollment_exit", "Enrollment"."exitReason" AS "Enrollment_exitReason", "Enrollment"."deletedDate" AS "Enrollment_deletedDate", "Enrollment"."authorId" AS "Enrollment_authorId", "Enrollment"."updatedAt" AS "Enrollment_updatedAt", "Enrollment_fundings"."id" AS "Enrollment_fundings_id", "Enrollment_fundings"."enrollmentId" AS "Enrollment_fundings_enrollmentId", "Enrollment_fundings"."deletedDate" AS "Enrollment_fundings_deletedDate", "Enrollment_fundings"."fundingSpaceId" AS "Enrollment_fundings_fundingSpaceId", "Enrollment_fundings"."firstReportingPeriodId" AS "Enrollment_fundings_firstReportingPeriodId", "Enrollment_fundings"."lastReportingPeriodId" AS "Enrollment_fundings_lastReportingPeriodId", "Enrollment_fundings"."authorId" AS "Enrollment_fundings_authorId", "Enrollment_fundings"."updatedAt" AS "Enrollment_fundings_updatedAt", "Enrollment_fundings_fundingSpace"."id" AS "Enrollment_fundings_fundingSpace_id", "Enrollment_fundings_fundingSpace"."capacity" AS "Enrollment_fundings_fundingSpace_capacity", "Enrollment_fundings_fundingSpace"."organizationId" AS "Enrollment_fundings_fundingSpace_organizationId", "Enrollment_fundings_fundingSpace"."source" AS "Enrollment_fundings_fundingSpace_source", "Enrollment_fundings_fundingSpace"."ageGroup" AS "Enrollment_fundings_fundingSpace_ageGroup", "Enrollment_fundings_fundingSpace"."time" AS "Enrollment_fundings_fundingSpace_time", "Enrollment_fundings_fundingSpace_timeSplit"."id" AS "Enrollment_fundings_fundingSpace_timeSplit_id", "Enrollment_fundings_fundingSpace_timeSplit"."fullTimeWeeks" AS "Enrollment_fundings_fundingSpace_timeSplit_fullTimeWeeks", "Enrollment_fundings_fundingSpace_timeSplit"."partTimeWeeks" AS "Enrollment_fundings_fundingSpace_timeSplit_partTimeWeeks", "Enrollment_fundings_fundingSpace_timeSplit"."fundingSpaceId" AS "Enrollment_fundings_fundingSpace_timeSplit_fundingSpaceId", "Enrollment_fundings_firstReportingPeriod"."id" AS "Enrollment_fundings_firstReportingPeriod_id", "Enrollment_fundings_firstReportingPeriod"."type" AS "Enrollment_fundings_firstReportingPeriod_type", "Enrollment_fundings_firstReportingPeriod"."period" AS "Enrollment_fundings_firstReportingPeriod_period", "Enrollment_fundings_firstReportingPeriod"."periodStart" AS "Enrollment_fundings_firstReportingPeriod_periodStart", "Enrollment_fundings_firstReportingPeriod"."periodEnd" AS "Enrollment_fundings_firstReportingPeriod_periodEnd", "Enrollment_fundings_firstReportingPeriod"."dueAt" AS "Enrollment_fundings_firstReportingPeriod_dueAt", "Enrollment_fundings_lastReportingPeriod"."id" AS "Enrollment_fundings_lastReportingPeriod_id", "Enrollment_fundings_lastReportingPeriod"."type" AS "Enrollment_fundings_lastReportingPeriod_type", "Enrollment_fundings_lastReportingPeriod"."period" AS "Enrollment_fundings_lastReportingPeriod_period", "Enrollment_fundings_lastReportingPeriod"."periodStart" AS "Enrollment_fundings_lastReportingPeriod_periodStart", "Enrollment_fundings_lastReportingPeriod"."periodEnd" AS "Enrollment_fundings_lastReportingPeriod_periodEnd", "Enrollment_fundings_lastReportingPeriod"."dueAt" AS "Enrollment_fundings_lastReportingPeriod_dueAt", "Enrollment_fundings_updateMetaData_author"."id" AS "Enrollment_fundings_updateMetaData_author_id", "Enrollment_fundings_updateMetaData_author"."wingedKeysId" AS "Enrollment_fundings_updateMetaData_author_wingedKeysId", "Enrollment_fundings_updateMetaData_author"."firstName" AS "Enrollment_fundings_updateMetaData_author_firstName", "Enrollment_fundings_updateMetaData_author"."lastName" AS "Enrollment_fundings_updateMetaData_author_lastName", "Enrollment_fundings_updateMetaData_author"."middleName" AS "Enrollment_fundings_updateMetaData_author_middleName", "Enrollment_fundings_updateMetaData_author"."suffix" AS "Enrollment_fundings_updateMetaData_author_suffix", "Enrollment_fundings_updateMetaData_author"."confidentialityAgreedDate" AS "Enrollment_fundings_updateMetaData_author_confidentialityAgreedDate", "Enrollment_updateMetaData_author"."id" AS "Enrollment_updateMetaData_author_id", "Enrollment_updateMetaData_author"."wingedKeysId" AS "Enrollment_updateMetaData_author_wingedKeysId", "Enrollment_updateMetaData_author"."firstName" AS "Enrollment_updateMetaData_author_firstName", "Enrollment_updateMetaData_author"."lastName" AS "Enrollment_updateMetaData_author_lastName", "Enrollment_updateMetaData_author"."middleName" AS "Enrollment_updateMetaData_author_middleName", "Enrollment_updateMetaData_author"."suffix" AS "Enrollment_updateMetaData_author_suffix", "Enrollment_updateMetaData_author"."confidentialityAgreedDate" AS "Enrollment_updateMetaData_author_confidentialityAgreedDate", "Enrollment__fundings"."id" AS "Enrollment__fundings_id", "Enrollment__fundings"."enrollmentId" AS "Enrollment__fundings_enrollmentId", "Enrollment__fundings"."deletedDate" AS "Enrollment__fundings_deletedDate", "Enrollment__fundings"."fundingSpaceId" AS "Enrollment__fundings_fundingSpaceId", "Enrollment__fundings"."firstReportingPeriodId" AS "Enrollment__fundings_firstReportingPeriodId", "Enrollment__fundings"."lastReportingPeriodId" AS "Enrollment__fundings_lastReportingPeriodId", "Enrollment__fundings"."authorId" AS "Enrollment__fundings_authorId", "Enrollment__fundings"."updatedAt" AS "Enrollment__fundings_updatedAt", "Enrollment__fundings_fundingSpace"."id" AS "Enrollment__fundings_fundingSpace_id", "Enrollment__fundings_fundingSpace"."capacity" AS "Enrollment__fundings_fundingSpace_capacity", "Enrollment__fundings_fundingSpace"."organizationId" AS "Enrollment__fundings_fundingSpace_organizationId", "Enrollment__fundings_fundingSpace"."source" AS "Enrollment__fundings_fundingSpace_source", "Enrollment__fundings_fundingSpace"."ageGroup" AS "Enrollment__fundings_fundingSpace_ageGroup", "Enrollment__fundings_fundingSpace"."time" AS "Enrollment__fundings_fundingSpace_time", "Enrollment__fundings_fundingSpace_timeSplit"."id" AS "Enrollment__fundings_fundingSpace_timeSplit_id", "Enrollment__fundings_fundingSpace_timeSplit"."fullTimeWeeks" AS "Enrollment__fundings_fundingSpace_timeSplit_fullTimeWeeks", "Enrollment__fundings_fundingSpace_timeSplit"."partTimeWeeks" AS "Enrollment__fundings_fundingSpace_timeSplit_partTimeWeeks", "Enrollment__fundings_fundingSpace_timeSplit"."fundingSpaceId" AS "Enrollment__fundings_fundingSpace_timeSplit_fundingSpaceId", "Enrollment__fundings_firstReportingPeriod"."id" AS "Enrollment__fundings_firstReportingPeriod_id", "Enrollment__fundings_firstReportingPeriod"."type" AS "Enrollment__fundings_firstReportingPeriod_type", "Enrollment__fundings_firstReportingPeriod"."period" AS "Enrollment__fundings_firstReportingPeriod_period", "Enrollment__fundings_firstReportingPeriod"."periodStart" AS "Enrollment__fundings_firstReportingPeriod_periodStart", "Enrollment__fundings_firstReportingPeriod"."periodEnd" AS "Enrollment__fundings_firstReportingPeriod_periodEnd", "Enrollment__fundings_firstReportingPeriod"."dueAt" AS "Enrollment__fundings_firstReportingPeriod_dueAt", "Enrollment__fundings_lastReportingPeriod"."id" AS "Enrollment__fundings_lastReportingPeriod_id", "Enrollment__fundings_lastReportingPeriod"."type" AS "Enrollment__fundings_lastReportingPeriod_type", "Enrollment__fundings_lastReportingPeriod"."period" AS "Enrollment__fundings_lastReportingPeriod_period", "Enrollment__fundings_lastReportingPeriod"."periodStart" AS "Enrollment__fundings_lastReportingPeriod_periodStart", "Enrollment__fundings_lastReportingPeriod"."periodEnd" AS "Enrollment__fundings_lastReportingPeriod_periodEnd", "Enrollment__fundings_lastReportingPeriod"."dueAt" AS "Enrollment__fundings_lastReportingPeriod_dueAt", "Enrollment__fundings_updateMetaData_author"."id" AS "Enrollment__fundings_updateMetaData_author_id", "Enrollment__fundings_updateMetaData_author"."wingedKeysId" AS "Enrollment__fundings_updateMetaData_author_wingedKeysId", "Enrollment__fundings_updateMetaData_author"."firstName" AS "Enrollment__fundings_updateMetaData_author_firstName", "Enrollment__fundings_updateMetaData_author"."lastName" AS "Enrollment__fundings_updateMetaData_author_lastName", "Enrollment__fundings_updateMetaData_author"."middleName" AS "Enrollment__fundings_updateMetaData_author_middleName", "Enrollment__fundings_updateMetaData_author"."suffix" AS "Enrollment__fundings_updateMetaData_author_suffix", "Enrollment__fundings_updateMetaData_author"."confidentialityAgreedDate" AS "Enrollment__fundings_updateMetaData_author_confidentialityAgreedDate" FROM "enrollment" "Enrollment" LEFT JOIN "funding" "Enrollment_fundings" ON "Enrollment_fundings"."enrollmentId"="Enrollment"."id" LEFT JOIN "funding_space" "Enrollment_fundings_fundingSpace" ON "Enrollment_fundings_fundingSpace"."id"="Enrollment_fundings"."fundingSpaceId" LEFT JOIN "funding_time_split" "Enrollment_fundings_fundingSpace_timeSplit" ON "Enrollment_fundings_fundingSpace_timeSplit"."fundingSpaceId"="Enrollment_fundings_fundingSpace"."id" LEFT JOIN "reporting_period" "Enrollment_fundings_firstReportingPeriod" ON "Enrollment_fundings_firstReportingPeriod"."id"="Enrollment_fundings"."firstReportingPeriodId" LEFT JOIN "reporting_period" "Enrollment_fundings_lastReportingPeriod" ON "Enrollment_fundings_lastReportingPeriod"."id"="Enrollment_fundings"."lastReportingPeriodId" LEFT JOIN "user" "Enrollment_fundings_updateMetaData_author" ON "Enrollment_fundings_updateMetaData_author"."id"="Enrollment_fundings"."authorId" LEFT JOIN "user" "Enrollment_updateMetaData_author" ON "Enrollment_updateMetaData_author"."id"="Enrollment"."authorId" LEFT JOIN "funding" "Enrollment__fundings" ON "Enrollment__fundings"."enrollmentId"="Enrollment"."id" LEFT JOIN "funding_space" "Enrollment__fundings_fundingSpace" ON "Enrollment__fundings_fundingSpace"."id"="Enrollment__fundings"."fundingSpaceId" LEFT JOIN "funding_time_split" "Enrollment__fundings_fundingSpace_timeSplit" ON "Enrollment__fundings_fundingSpace_timeSplit"."fundingSpaceId"="Enrollment__fundings_fundingSpace"."id" LEFT JOIN "reporting_period" "Enrollment__fundings_firstReportingPeriod" ON "Enrollment__fundings_firstReportingPeriod"."id"="Enrollment__fundings"."firstReportingPeriodId" LEFT JOIN "reporting_period" "Enrollment__fundings_lastReportingPeriod" ON "Enrollment__fundings_lastReportingPeriod"."id"="Enrollment__fundings"."lastReportingPeriodId" LEFT JOIN "user" "Enrollment__fundings_updateMetaData_author" ON "Enrollment__fundings_updateMetaData_author"."id"="Enrollment__fundings"."authorId" WHERE ( "Enrollment"."childId" = @0 ) AND ( "Enrollment"."deletedDate" IS NULL ) -- PARAMETERS: ["redacted"]
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: TypeError: Cannot read property 'periodStart' of null
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at /var/app/current/dist/src/entity/decorators/Funding/fundingOverlapValidation.js:33:42
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at Array.forEach (<anonymous>)
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at Object.validate (/var/app/current/dist/src/entity/decorators/Funding/fundingOverlapValidation.js:31:42)
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at CustomConstraint.validate (/var/app/current/node_modules/class-validator/bundles/index.umd.js:796:40)
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at /var/app/current/node_modules/class-validator/bundles/index.umd.js:482:80
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at Array.forEach (<anonymous>)
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at /var/app/current/node_modules/class-validator/bundles/index.umd.js:471:22
	2021-01-29T09:32:41.904-05:00
Jan 29 14:32:41 ip-10-0-40-147 web: at Array.forEach (<anonymous>)
	Jan 29 14:32:41 ip-10-0-40-147 web: at Array.forEach (<anonymous>)
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at ValidationExecutor.customValidations (/var/app/current/node_modules/class-validator/bundles/index.umd.js:468:23)
	2021-01-29T09:32:41.904-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: at ValidationExecutor.performValidations (/var/app/current/node_modules/class-validator/bundles/index.umd.js:439:18)
	2021-01-29T09:32:46.158-05:00	Jan 29 14:32:41 ip-10-0-40-147 web: ::ffff:127.0.0.1 - 1 [29/Jan/2021:14:32:41 +0000] "GET /api/children?organizationId=3&skip=0&take=100 HTTP/1.0" 500 67
```

## Acceptance Criteria
- validation no longer causes error and query proceeds correctly
- 500s on roster query are handled in the app (error boundary?)

**Comment by JordanGuinn** [comment]
It's easy enough to handle a 500 response to the roster query on initial page load, but I'm wondering what the UX should be if the roster query suddenly fails 3 or 4 pages in?  Or if that's even worth worrying about here? 😅

**Comment by jlhogan** [comment]
My vote: not worth worrying about here; approx 3% of rosters have more than one page
